### ISSUE TITLE
FR: Add destroy Fitbit token option

### ISSUE THREAD

**Issue by lesaff** [simonepri/fitbit2garmin#2]
@simonepri I think it would it be useful to add `destroy-fitbit-token` to the command parameter, so that it can be used to export from multiple Fitbit accounts. What do you think?

If you're too busy, I can fork this repo and try it myself. I am not a python programmer, so I don't know how it works, but if you can point out where in the codebase I can add this, it would be awesome! Thanks!

**UPDATE**: No worries, I just found out that I can revoke my Fitbit token directly from the Fitbit app dashboard.

**Comment by simonepri** [comment]
>  think it would it be useful to add destroy-fitbit-token

I agree, it's rather simple to add but in the meantime you simply run `rm .cache/.auth` from the folder where you decided to export the data to reset authentication.

> so that it can be used to export from multiple Fitbit accounts

If you want to export multiple accounts just export them to two separate folders.
