### ISSUE TITLE
Activity & Weight Data are missing file extension

### ISSUE THREAD

**Issue by Lordpaulson** [simonepri/fitbit2garmin#4]
@simonepri  - Firstly, thanks for this awesome tool. However, the Activity and Weight files do not have an extension and the garmin tool does not seem to like that. The GPS ones are good and have the .tcx extension. Can you please advice what is the recommended file format or extension for the other two?

**Comment by Lordpaulson** [comment]
Also, I see that these are 0KB files - So, Looks lke the data never came through. 
<img width="551" alt="image" src="https://github.com/simonepri/fitbit2garmin/assets/153989719/c0757623-aaff-462b-9b7b-8b01d5c2726c">

**Comment by simonepri** [comment]
Hi @Lordpaulson, can you provide the command you run and your OS/python versions?

The output you are getting is rather odd, the script should export these exstensionless empty files only inside a hidden `.cache` folder.

**Comment by Lordpaulson** [comment]
Here you go, @simonepri . Here is the version info:
Python 3.11.7, Pip 23.3.1, git version 2.43.0.windows.1, OS- Win 11 23H2 (Build - 22631.2861)
<img width="715" alt="image" src="https://github.com/simonepri/fitbit2garmin/assets/153989719/6467c65a-7121-4154-95b3-7d5e2c8aa1fa">


This is the command I ran:
PS C:\Users\krpaulson\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts> .\fitbit2garmin.exe dump-all --start-date 2013-10-22
<img width="783" alt="image" src="https://github.com/simonepri/fitbit2garmin/assets/153989719/834185c4-10d1-4dce-aed5-7c2818397044">

**Comment by simonepri** [comment]
@Lordpaulson sorry for the late reply it took me a while to get a machine with windows to debug this because I couldn't see any obvious reason for this to happen. At end it seems that the issue was that the filenames that the CLI was trying to write had a colon (:) character in it and Windows does not support filenames with colons. 

Just uninstall and re-install the package to get the fix and everything should work.

**Comment by Lordpaulson** [comment]
Thanks a ton, @simonepri ! It is working just fine! Appreciate the help and timely support!
